_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 55
            "4": 3.10.5
            "5": 0.20.1
            "8":
                - 1
                - 3
            "12": 0.20.1
            "13": windows-amd64
model:
    value: Shallow_Neural_Network
num_classes:
    value: 7
phase:
    value: test
