_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.5
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 55
            "4": 3.10.5
            "5": 0.20.1
            "8":
                - 1
                - 3
            "12": 0.20.1
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 150
input_dim:
    value: 35
learning_rate:
    value: 0.0005
model:
    value: LSTM_Model
num_classes:
    value: 7
